x-openedx-service:
  &openedx-service
  image: openedx-dev:18.1.2
  stdin_open: true
  tty: true
  volumes:
    # theme files
    - ../build/openedx/themes:/openedx/themes

services:
  permissions:
    environment:
      OPENEDX_USER_ID: "1000"

  lms:
    <<: *openedx-service
    command: ./manage.py lms runserver 0.0.0.0:8000
    environment:
        DJANGO_SETTINGS_MODULE: lms.envs.tutor.development
    ports:
        - "8000:8000"
    networks:
      default:
        aliases:
          - "openedx.ryumatsu.com"

  cms:
    <<: *openedx-service
    command: ./manage.py cms runserver 0.0.0.0:8000
    environment:
        DJANGO_SETTINGS_MODULE: cms.envs.tutor.development
    ports:
        - "8001:8000"

  lms-worker:
    <<: *openedx-service

  cms-worker:
    <<: *openedx-service

  # Additional service for watching theme changes
  watchthemes:
    <<: *openedx-service
    command: npm run watch-sass
    restart: unless-stopped

  

  forum:
    stdin_open: true
    tty: true
  mfe:
      ports:
          - 1999:8002 # authn
          - 1997:8002 # account
          - 1984:8002 # communications
          - 2001:8002 # course-authoring
          - 2002:8002 # discussions
          - 1994:8002 # gradebook
          - 1996:8002 # learner-dashboard
          - 2000:8002 # learning
          - 1993:8002 # ora-grading
          - 1995:8002 # profile