SITE_NAME: "openedx.ryumatsu.com"
BOOK_URL: ""
LOG_DIR: "/openedx/data/logs"
LOGGING_ENV: "sandbox"
OAUTH_OIDC_ISSUER: "https://openedx.ryumatsu.com/oauth2"
PLATFORM_NAME: "Test for Prep courses"
FEATURES:
   CERTIFICATES_HTML_VIEW: true
   PREVIEW_LMS_BASE: "preview.openedx.ryumatsu.com"
   ENABLE_COURSE_DISCOVERY: true
   ENABLE_COURSEWARE_SEARCH: true
   ENABLE_CSMH_EXTENDED: false
   ENABLE_DASHBOARD_SEARCH: true
   ENABLE_COMBINED_LOGIN_REGISTRATION: true
   ENABLE_GRADE_DOWNLOADS: true
   ENABLE_LEARNER_RECORDS: false
   ENABLE_MOBILE_REST_API: true
   ENABLE_OAUTH2_PROVIDER: true
   ENABLE_PREREQUISITE_COURSES: true
   ENABLE_THIRD_PARTY_AUTH: true
   MILESTONES_APP: true
LMS_ROOT_URL: "https://openedx.ryumatsu.com"
CMS_ROOT_URL: "https://studio.openedx.ryumatsu.com"
CMS_BASE: "studio.openedx.ryumatsu.com"
LMS_BASE: "openedx.ryumatsu.com"
CONTACT_EMAIL: "hello@openedx.ryumatsu.com"
CELERY_BROKER_TRANSPORT: "redis"
CELERY_BROKER_HOSTNAME: "redis:6379"
CELERY_BROKER_VHOST: "0"
CELERY_BROKER_USER: ""
CELERY_BROKER_PASSWORD: ""
ALTERNATE_WORKER_QUEUES: "cms"
ENABLE_COMPREHENSIVE_THEMING: true
EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST: "smtp.ionos.com"
EMAIL_PORT: 587
EMAIL_USE_TLS: true
ACE_ROUTING_KEY: "edx.lms.core.default"
HTTPS: "on"
LANGUAGE_CODE: "en"
SESSION_COOKIE_DOMAIN: "openedx.ryumatsu.com"
COMMENTS_SERVICE_URL: "http://forum:4567"
COMMENTS_SERVICE_KEY: "forumapikey"
SECRET_KEY: "lEs3Z4JofFDz0TFoQnPlqWPg"
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""
DOC_STORE_CONFIG: null

XQUEUE_INTERFACE:
   django_auth: null
   url: null
DATABASES:
   default:
      ENGINE: "django.db.backends.mysql"
      HOST: "mysql"
      PORT: 3306
      NAME: "openedx"
      USER: "openedx"
      PASSWORD: "oZ2f20Fm"
      ATOMIC_REQUESTS: true
      OPTIONS:
         init_command: "SET sql_mode='STRICT_TRANS_TABLES'"
         charset: "utf8mb4"
EMAIL_HOST_USER: ""
EMAIL_HOST_PASSWORD: ""
